---
# tasks file for nginx
- name: Creating the nginx config file
  copy:
    dest: "/etc/nginx/conf.d/http.conf"
    content: |
      server {
        server_name rpi5.reems.org {{ nebulaVPNIp }};  # Voeg het IP-adres toe aan de server_name

        client_max_body_size 100M;

        error_log /var/log/nginx/http.error;

        # Home Assistant als standaard locatie (root)
        location / {
            proxy_pass http://127.0.0.1:8123;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        location /joplin/ {
            proxy_pass http://127.0.0.1:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # Zorg ervoor dat de X-Forwarded-For-header goed is ingesteld
            proxy_set_header X-Forwarded-Proto $scheme;  # Voeg deze regel toe om het juiste protocol door te geven
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-Host $host;
            client_max_body_size 400M;
        }

        location /searxng/ {
            proxy_pass http://127.0.0.1:8081/;  # Update to the new port
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # Zorg ervoor dat de X-Forwarded-For-header goed is ingesteld
            proxy_set_header X-Forwarded-Proto $scheme;  # Voeg deze regel toe om het juiste protocol door te geven
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-Host $host;
            client_max_body_size 400M;
            proxy_http_version 1.1;
            proxy_set_header Connection "keep-alive";

        }
      }
  notify: 
  - Enable and ensure nginx is started
  - Restart nginx
