---
# tasks file for nginx
- name: Creating the nginx config file
  copy:
    dest: "/etc/nginx/conf.d/joplin-server.conf"
    content: |
      server {
        server_name joplin.reems.org {{ nebulaVPNIp }};  # Voeg het IP-adres toe aan de server_name

        client_max_body_size 100M;

        error_log /var/log/nginx/joplin-server.error;

        location /joplin/ {
            proxy_pass http://127.0.0.1:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # Zorg ervoor dat de X-Forwarded-For-header goed is ingesteld
            proxy_set_header X-Forwarded-Proto $scheme;  # Voeg deze regel toe om het juiste protocol door te geven
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-Host $host;
            client_max_body_size 400M;
        }

        listen 80;
        listen [::]:80;
      }
  notify: Enable and ensure nginx is started