---
- hosts: all
  become: true

  tasks:
  - include_role:
      name: apt-role
    vars: 
      aptPackagesToInstall: "{{ aptPackages }}"

  - include_role:
      name: joplinServer

  - include_role:
      name: home_assistant

  - include_role:
      name: nginx

  # - include_role:
  #     name: pip-role
  #   vars:
  #     pipPackagesToInstall: "{{ pipPackages }}"

  # - include_role:
  #     name: rvr-powersurpluslogger-role
  #   vars:
  #     user: robert