---
- hosts: all
  tasks:
  - include_role:
      name: pip-role
    vars:
      pipPackagesToInstall: "{{ pipPackages }}"

  - include_role:
      name: rvr-powersurpluslogger-role
    vars:
      user: robert