---
# handlers file for nginx
- name: Enable and ensure nginx is started
  become: true
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Restart nginx
  service:
    name: nginx
    state: restarted