userslist:
  - name: robert
    fullname: Robert van Reems
    email: "robertreems@gmail.com"

aptPackages:
  - git # can be removed todo
  - acl #fixes rpi issue https://github.com/georchestra/ansible/issues/55
  - vim
  - screen

pipPackages:
  - rvr-base==1.0.0

# Hue bridge dongle:
hueIP: 10.0.0.3

# Home wizzard P1 dongle IP:
hwip: 10.0.0.4

# Azure Log analytics
log_analytics_workspace_id: 7756814b-7720-4b6d-9fb6-0aa03fe97658

# sensitive data
robert_password: "{{ vault_robert_password }}"
ansible_become_pass: "{{ vault_master_password }}" # the sudo password for the local session.
git_token: "{{ vault_git_token }}"
log_analytics_primary_key: "{{ log_analytics_primary_key }}"
