aptPackages:
  - screen
  - nginx
  - docker-compose
  - vim

nebulaVPNIp: 192.168.100.17
docker_compose_version: "v2.20.2"
data_dir: "/opt/joplin/data"
ports:
  - "22300:22300"  # Joplin Server API
  - "22301:22301"  # Joplin Sync Target

# sensitive data
ansible_become_pass: "{{ vault_master_password }}" # the sudo password for the local session.
